import { createRootRoute, HeadContent, Outlet, Scripts } from "@tanstack/react-router";
import type { ErrorComponentProps } from "@tanstack/react-router";
import { useEffect } from "react";
import { ClerkProvider } from "@clerk/tanstack-react-start";
import { Toaster } from "react-hot-toast";
import { Provider } from "~/app/_providers/QueryProvider";
import ThemeContextProvider from "~/context/ThemeContext";
import Navbar from "~/app/_components/Navbar";
import ThemeSwitch from "~/app/_components/ThemeSwitch";
import "ag-grid-enterprise";
import "~/styles/globals.css";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { title: "FantasyFive FFL" },
      { name: "description", content: "Generated by create-t3-app" },
    ],
    links: [{ rel: "icon", href: "/favicon.ico" }],
  }),
  component: RootComponent,
  errorComponent: RootErrorComponent,
});

function RootComponent() {
  return (
    <RootDocument>
      <Outlet />
    </RootDocument>
  );
}

function RootErrorComponent({ error, reset }: ErrorComponentProps) {
  useEffect(() => {
    console.error(error);
  }, [error]);

  return (
    <RootDocument>
      <div>
        <h2>Something went wrong!</h2>
        <button onClick={() => reset()}>Try again</button>
      </div>
    </RootDocument>
  );
}

function RootDocument({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body className="font-sans">
        <ClerkProvider>
          <Provider>
            <ThemeContextProvider>
              <div className="min-h-screen transition-all dark:bg-slate-800">
                <Toaster />
                <Navbar />
                {children}
                <ThemeSwitch />
              </div>
            </ThemeContextProvider>
          </Provider>
        </ClerkProvider>
        <Scripts />
      </body>
    </html>
  );
}
